version: '3.7'

services: 
    nginx: 
        image: nginx:latest
        container_name: nginx
        restart: unless-stopped
        tty: true
        ports: 
            - '8888:80'
        volumes: 
            - ./www:/var/www
            - ./nginx/conf.d/:/etc/nginx/conf.d/
            - ./nginx/log/access.log:/var/log/nginx/access.log
            - ./nginx/log/error.log:/var/log/nginx/error.log
        depends_on: 
            - web
        networks: 
            - web-network
    
    web:
        build: 
            context: ./php
            dockerfile: Dockerfile
        volumes: 
            - ./www:/var/www
        restart: unless-stopped
        container_name: php
        depends_on: 
            - redis
        tty: true
        networks: 
            - web-network
    redis:
        image: redis:latest
        container_name: redis
        restart: unless-stopped
        volumes: 
            - ./redis/data:/data
        ports:
            - '6377:6379'
        command: ['redis-server']
        hostname: redis
        networks: 
            - web-network

networks: 
    web-network:
        driver: bridge

volumes: 
    dbdata:
        driver: local